엔티티 매핑
nhn-academy/eggplant-delivery pull request #2
Opened 2022-07-27 15:34 UTC by Irisation23

#1

## 작업 내용

1. 배송 정보 Entity 생성
2. 위치 Entity 생성

2022-07-27 16:36 UTC, JoisFe commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
> +    @ManyToOne
단방향으로 선택한 이유를 알 수 있을까요?

2022-07-27 16:36 UTC, JoisFe commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +}
convention상 41번쨰줄 이후 개행이 필요해 보입니다.

2022-07-27 16:36 UTC, JoisFe commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
> +}
이 부분도 마찬가지로 개행이 필요해 보입니다.

2022-07-27 16:36 UTC, JoisFe commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
> +}
이 부분도 개행 부탁드려요. ^^

2022-07-28 01:11 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +}
넵 적용 완료했습니다.

2022-07-28 01:11 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
> +}
네넵 반영했습니다.

2022-07-28 01:12 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
> +}
개행 전반적으로 푸시전에 확인하겠습니다.

2022-07-28 01:19 UTC, corock requested changes

2022-07-28 01:19 UTC, corock commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +    private Long slipNo;
*slip* 이 무슨 의미인가요?

2022-07-28 01:19 UTC, corock commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
> + * 배송정보의 상태를
Javadoc 이 미완성인 것 같습니다.

2022-07-28 01:21 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
> +    @ManyToOne
- 현재 테이블 구조에서는 단방향 매핑만으로도 구현하는데 크게 지장이 없다고 판단되었고,
- 연관관계 주인이 `Location` 인데 역방향 탐색이 일어날 상황 (`Dlivery Info` 가 `Location` 을 탐색하는 상황) 이 현재 구현에서는 없다고 판단 되었습니다.
- 만약 차후 구현에서 양방향 매핑이 필요하게 된다면 그때 추가 하도록 하겠습니다. 🙇🏻‍♂️

2022-07-28 01:29 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
> + * 배송정보의 상태를
수정했습니다~

2022-07-28 01:32 UTC, JoisFe commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
slip_no이 운송장 번호로 알고있는데 이렇게 되면 해당 부분은 하면 안되지 않을까요?

2022-07-28 01:44 UTC, Irisation23 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +    private Long slipNo;
해당 테이블은 운송장 번호로 PK 를 설정 해두었습니다.
운송장 번호가 CJ 대한통운에서 사용 되었고, 외국에서 간혹 사용 되었다고 알고 있었는데
좀 더 저희에게 명확한 표현은 tracking_no 이 좀 더 맞다고 생각되네요. 변경후 커밋하겠습니다.

2022-07-28 01:46 UTC, bunsung92 commented on src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
해당 부분처리를 `@GeneratedValue` 를 처리하면 안된다라고 판단이 되는데,  수정하도록 하겠습니다.

2022-07-29 01:45 UTC, corock approved these changes

2022-07-29 01:51 UTC, JoisFe approved these changes

2022-07-29 01:53 UTC, merged